var express = require('express');
var router = express.Router();
var csrf = require('csurf');
var csrfProtection = csrf();
router.use(csrfProtection);
var admin_controller = require('../controllers/adminController');

router.get('/login', admin_controller.login);
router.post('/login', admin_controller.login_form_post);
router.get('/logout', admin_controller.logout);
router.get('/',admin_controller.isLoggedInLv1, admin_controller.dashboard);
router.get('/product',admin_controller.isLoggedInLv1, admin_controller.product_admin);
router.get('/user',admin_controller.isLoggedInLv1, admin_controller.user_admin);
router.get('/product/add',admin_controller.isLoggedInLv2, admin_controller.add_product);
router.post('/product/add',admin_controller.isLoggedInLv2, admin_controller.add_product_post);
router.get('/product/edit/:id',admin_controller.isLoggedInLv2,admin_controller.product_edit_get);
router.post('/product/edit/:id',admin_controller.isLoggedInLv2,admin_controller.product_edit_post);
router.get('/user/edit/:id',admin_controller.isLoggedInLv3,admin_controller.user_edit_get);
router.post('/user/edit/:id',admin_controller.isLoggedInLv3,admin_controller.user_edit_post);
router.get('/product/delete/:id',admin_controller.isLoggedInLv2,admin_controller.product_delete);
router.get('/order',admin_controller.isLoggedInLv1, admin_controller.order_admin);
router.get('/order_detail/:id',admin_controller.isLoggedInLv2, admin_controller.order_detail_admin);
module.exports = router;